CREATE TABLE propP AS SELECT * FROM olga.propP;

ALTER TABLE propP
ADD (CONSTRAINT pk_propP PRIMARY KEY(idR, idP),
	CONSTRAINT fk_idR FOREIGN KEY(idR) REFERENCES resto(idR),
	CONSTRAINT fk_idP FOREIGN KEY(idP) REFERENCES plat(idP)
	);
	
