# Fichier makefile

proc2: p2fils1.o p2fils2.o proc2.o
	gcc -o proc2 p2fils1.o p2fils2.o proc2.o

p2fils1.o: p2fils1.c
	gcc -c p2fils1.c

p2fils2.o: p2fils2.c
	gcc -c p2fils2.c

proc2.o: proc2.c
	gcc -c proc2.c
