default: signal1-fifo signal2-fifo reception emission

signal1-fifo: signal1-fifo.c
	gcc -o signal1-fifo signal1-fifo.c

signal2-fifo: signal2-fifo.c
	gcc -o signal2-fifo signal2-fifo.c

reception: reception.c
	gcc -o reception reception.c

emission: emission.c
	gcc -o emission emission.c
