package ex2;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author aroquemaurel
 */
public class Ex2UsTricolor extends javax.swing.JFrame {
    private enum States {INIT, RED, GREEN, ORANGE, RED_ORANGE, ONPANNE, OFFPANNE};
    
    /**
     * Creates new form Ex2UsTricolor
     */
    public Ex2UsTricolor() {
        initComponents();
        initRedTimer();
        initOrangeTimer();
        initGreenTimer();
        initRedOrangeTimer();
        initOffPaneTimer();
        initOnPanneTimer();
        init();
    }

    private void init() {
        turnOffAll();
        state = States.INIT;
        initActivation();
    }
    
    private void turnOnOrange() {
        turnOffAll();
        orangeLabel.setIcon(new ImageIcon(getClass().getResource("/tricolors/tricolor_orange.png")));        
    }
    
    private void turnOnGreen() {
        turnOffAll();
        greenLabel.setIcon(new ImageIcon(getClass().getResource("/tricolors/tricolor_green.png")));        
    }
    
    private void turnOnRed() {
        turnOffAll();
        redLabel.setIcon(new ImageIcon(getClass().getResource("/tricolors/tricolor_red.png")));
    }
    private void turnOnRedOrange() {
        turnOffAll();
        redLabel.setIcon(new ImageIcon(getClass().getResource("/tricolors/tricolor_red.png")));
        orangeLabel.setIcon(new ImageIcon(getClass().getResource("/tricolors/tricolor_orange.png")));        
    }
    private void turnOffAll() {
        redLabel.setIcon(new ImageIcon(getClass().getResource("/tricolors/tricolor_off.png")));
        greenLabel.setIcon(new ImageIcon(getClass().getResource("/tricolors/tricolor_off.png")));
        orangeLabel.setIcon(new ImageIcon(getClass().getResource("/tricolors/tricolor_off.png")));
    }
    
    private void initActivation() {
        onButton.setEnabled(true);
        offButton.setEnabled(false);
        panneButton.setEnabled(false);
        redTimer.stop();
        greenTimer.stop();
        orangeTimer.stop();
        onPanneTimer.stop();
        offPanneTimer.stop();
        redOrangeTimer.stop();
    }
    
    private void redActivation() {
        onButton.setEnabled(false);
        offButton.setEnabled(true);
        panneButton.setEnabled(true);        
        redTimer.start();
        orangeTimer.stop();
        greenTimer.stop();
        onPanneTimer.stop();
        offPanneTimer.stop();
        redOrangeTimer.stop();
    }
    
    private void greenActivation() {
        onButton.setEnabled(false);
        offButton.setEnabled(true);
        panneButton.setEnabled(true);               
        redTimer.stop();
        greenTimer.start();
        orangeTimer.stop();
        onPanneTimer.stop();
        offPanneTimer.stop();
        redOrangeTimer.stop();
    }
    
    private void orangeActivation() {
        onButton.setEnabled(false);
        offButton.setEnabled(true);
        panneButton.setEnabled(true);        
        redTimer.stop();
        greenTimer.stop();
        orangeTimer.start();
        onPanneTimer.stop();
        offPanneTimer.stop();
        redOrangeTimer.stop();
    }
    
    private void redOrangeActivation() {
        onButton.setEnabled(false);
        offButton.setEnabled(true);
        panneButton.setEnabled(true);        
        redTimer.stop();
        greenTimer.stop();
        orangeTimer.stop();
        onPanneTimer.stop();
        offPanneTimer.stop();
        redOrangeTimer.start();

    }
    
    private void onPanneActivation() {
        onButton.setEnabled(false);
        offButton.setEnabled(true);
        panneButton.setEnabled(false);      
        onPanneTimer.start();
        offPanneTimer.stop();
        redTimer.stop();
        greenTimer.stop();
        orangeTimer.stop();
        redOrangeTimer.stop();
    }
    
    private void offPanneActivation() {
        onButton.setEnabled(false);
        offButton.setEnabled(true);
        panneButton.setEnabled(false);                
        onPanneTimer.stop();
        offPanneTimer.start();
        redTimer.stop();
        greenTimer.stop();
        orangeTimer.stop();
        redOrangeTimer.stop();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        redLabel = new javax.swing.JLabel();
        orangeLabel = new javax.swing.JLabel();
        greenLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        onButton = new javax.swing.JButton();
        panneButton = new javax.swing.JButton();
        offButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(250, 480));

        jPanel2.setMinimumSize(new java.awt.Dimension(150, 200));
        jPanel2.setLayout(new java.awt.GridLayout(3, 1));

        redLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(redLabel);

        orangeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(orangeLabel);

        greenLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(greenLabel);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        onButton.setText("Marche");
        onButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onButtonActionPerformed(evt);
            }
        });
        jPanel1.add(onButton);

        panneButton.setText("Panne");
        panneButton.setMaximumSize(new java.awt.Dimension(86, 25));
        panneButton.setMinimumSize(new java.awt.Dimension(86, 25));
        panneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panneButtonActionPerformed(evt);
            }
        });
        jPanel1.add(panneButton);

        offButton.setText("Arrêt");
        offButton.setMaximumSize(new java.awt.Dimension(86, 25));
        offButton.setMinimumSize(new java.awt.Dimension(86, 25));
        offButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offButtonActionPerformed(evt);
            }
        });
        jPanel1.add(offButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void redTimerActionPerformed() {
        switch(state) {
            case RED:
                state = States.RED_ORANGE;
                turnOnRedOrange();
                redOrangeActivation();
                break;
            case ONPANNE:
            case OFFPANNE:
            case ORANGE:
            case GREEN:
            case INIT:
            case RED_ORANGE:                
                throw new RuntimeException("bad state");                                
        }
    }

    private void greenTimerActionPerformed() {
        switch(state) {
            case GREEN:
                state = States.ORANGE;
                turnOnOrange();                                
                orangeActivation();
                break;
            case ONPANNE:
            case OFFPANNE:
            case RED:
            case ORANGE:
            case INIT:
            case RED_ORANGE:
                throw new RuntimeException("bad state");                                
        }

    }

    private void orangeTimerActionPerformed() {
        switch(state) {
            case ORANGE:
                state = States.RED;
                turnOnRed();
                redActivation();
                break;
            case ONPANNE:
            case OFFPANNE:
            case RED:
            case GREEN:
            case INIT:
            case RED_ORANGE:
                throw new RuntimeException("bad state");                
        }
    }                
    
    private void redOrangeTimerActionPerformed() {
        switch(state) {
            case RED_ORANGE:
                state = States.GREEN;
                turnOnGreen();
                greenActivation();
                break;
            case ORANGE:
            case ONPANNE:
            case OFFPANNE:
            case RED:
            case GREEN:
            case INIT:
                throw new RuntimeException("bad state");                
        }

    }

    private void offPanneTimerActionPerformed() {
        switch(state) {
            case OFFPANNE:
                state = States.ONPANNE;
                turnOnOrange();
                onPanneActivation();
                break;
            case ORANGE:
            case ONPANNE:
            case RED:
            case GREEN:
            case INIT:
                throw new RuntimeException("bad state");
        }
    }

    private void onPanneTimerActionPerformed() {
        switch(state) {
            case ONPANNE:
                state = States.OFFPANNE;
                turnOffAll();
                offPanneActivation();
                break;
            case ORANGE:
            case OFFPANNE:
            case RED:
            case GREEN:
            case INIT:
                throw new RuntimeException("bad state");
        }
    }
    
    private void onButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onButtonActionPerformed
        switch(state) {
            case INIT:
                state = States.RED;
                turnOnRed();
                redActivation();
                break;
            case ORANGE:
            case RED:
            case GREEN:
            case ONPANNE:
            case OFFPANNE:
                throw new RuntimeException("Bad state !");
        }
    }//GEN-LAST:event_onButtonActionPerformed
        
    private void panneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panneButtonActionPerformed
        switch(state) {
            case ORANGE:
            case RED:
            case GREEN:
                state = States.ONPANNE;
                turnOnOrange();                
                onPanneActivation();
                break;            
            case ONPANNE:
            case OFFPANNE:
            case INIT:
                throw new RuntimeException("Bad state !");            
        }
    }//GEN-LAST:event_panneButtonActionPerformed

    private void offButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offButtonActionPerformed
        switch(state) {
            case INIT:
                throw new RuntimeException("Bad state !");            
            case ORANGE:
            case RED:
            case GREEN:
            case ONPANNE:
            case OFFPANNE:
                state = States.INIT;
                turnOffAll();
                initActivation();
        }
    }//GEN-LAST:event_offButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ex2UsTricolor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ex2UsTricolor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ex2UsTricolor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ex2UsTricolor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ex2UsTricolor().setVisible(true);
            }
        });
    }
    
    
    private void initRedTimer() {
            redTimer = new Timer(RED_TIME, new ActionListener() {
 
            @Override
            public void actionPerformed(ActionEvent e) {
                redTimerActionPerformed();
            }          
        });
    
    }
    
    private void initOrangeTimer() {
        orangeTimer = new Timer(ORANGE_TIME, new ActionListener() {
 
            @Override
            public void actionPerformed(ActionEvent e) {
                orangeTimerActionPerformed();
            }          
             
        });
    }
    private void initRedOrangeTimer() {
        redOrangeTimer = new Timer(RED_ORANGE_TIME, new ActionListener() {
 
            @Override
            public void actionPerformed(ActionEvent e) {
                redOrangeTimerActionPerformed();
            }          
             
        });
    }
    private void initGreenTimer() {
            greenTimer = new Timer(GREEN_TIME, new ActionListener() {
 
            @Override
            public void actionPerformed(ActionEvent e) {
                greenTimerActionPerformed();
            }          
             
        });
    
    }
    
    private void initOnPanneTimer() {
        onPanneTimer = new Timer(PANNE_ON_TIME, new ActionListener() {
 
            @Override
            public void actionPerformed(ActionEvent e) {
                onPanneTimerActionPerformed();
            }          
             
        });
 
    }
    
    private void initOffPaneTimer() {
        offPanneTimer = new Timer(PANNE_OFF_TIME, new ActionListener() {
 
            @Override
            public void actionPerformed(ActionEvent e) {
                offPanneTimerActionPerformed();
            }          
             
        });
    }
    private States state;
    private Timer redTimer;
    private Timer orangeTimer;
    private Timer greenTimer;
    private Timer onPanneTimer;
    private Timer offPanneTimer;
    private Timer redOrangeTimer;
    
    private final int RED_TIME = 2000;
    private final int ORANGE_TIME = 500;
    private final int GREEN_TIME = 1500;
    private final int RED_ORANGE_TIME = 1000;

    private final int PANNE_ON_TIME = 600;
    private final int PANNE_OFF_TIME = 400;
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel greenLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton offButton;
    private javax.swing.JButton onButton;
    private javax.swing.JLabel orangeLabel;
    private javax.swing.JButton panneButton;
    private javax.swing.JLabel redLabel;
    // End of variables declaration//GEN-END:variables
}
