/*
 * DialogHelp.java
 *
 * Created on 20 août 2008, 13:32
 */

package satoulouse;

/**
 *
 * @author  proprietaire
 */
public class DialogHelp extends javax.swing.JDialog {


    /** Creates new form DialogHelp */
    public DialogHelp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        page_show("satoulouse.html");
    }
    
    
    



    void page_show(String name)
    {
        helpPanel.page_show(name);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        helpPanel = new satoulouse.HelpPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(satoulouse.SatoulouseApp.class).getContext().getResourceMap(DialogHelp.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setMinimumSize(new java.awt.Dimension(500, 400));
        setName("Form"); // NOI18N

        helpPanel.setName("helpPanel"); // NOI18N
        getContentPane().add(helpPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogHelp dialog = new DialogHelp(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private satoulouse.HelpPanel helpPanel;
    // End of variables declaration//GEN-END:variables

}
