/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SATResults.java
 *
 * Created on 26 sept. 2010, 02:57:12
 */

package satoulouse;

import java.util.ArrayList;
import javax.swing.JLabel;

/**
 * Ceci est la fenêtre de résultat qui dit :
 * insatisfiable si l'ensemble est insatisfiable
 * satisfiable et donne une valuation si l'ensemble est satisfiable
 * @author François Schwarzentruber
 */
public class SATResults extends javax.swing.JDialog {

    //contient l'ensemble des propositions vraies
    ArrayList<String> propositionsVraies;



/**
 * affiche la valuation en utilisant propositionsVraies
 * et le filtre txtSelection.getText()
 */
    private void afficherValuation()
    {
        String filtre = txtSelection.getText();
        panValuationProposition.removeAll();

        for(String s : propositionsVraies)
        {
            if(s.indexOf(filtre) >= 0)
                try
                {
                    if(panValuationProposition.getComponents().length > 0)
                        panValuationProposition.add(new JLabel(", "));

                   panValuationProposition.add(new JLabel(LaTEX.latexCodeToImageIcon(FormulaBox.formulaSchemeStringToLatexCode(s))));
                }
                catch(Exception e)
                {
                    System.out.println("Problème pour produire le code LaTEX d'une proposition : " + s);
                }
        }
        panValuationProposition.doLayout();
        panValuationProposition.repaint();
    }


    /** Creates new form SATResults */
    public SATResults(java.awt.Frame parent, boolean modal, ArrayList<String> results) {
        super(parent, modal);
        
        initComponents();
        this.propositionsVraies = results;
        
        if(results != null)
        {
            panSatisfiable.setVisible(true);
            panInsatisfiable.setVisible(false);
            panValuation.setVisible(true);

            afficherValuation();
                
                   
        }
        else
        {
            panInsatisfiable.setVisible(true);
            panSatisfiable.setVisible(false);
            panValuation.setVisible(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panSatisfiable = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panInsatisfiable = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panValuation = new javax.swing.JPanel();
        panValuationProposition = new javax.swing.JPanel();
        panSelection = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtSelection = new javax.swing.JTextField();
        cmdHelp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(satoulouse.SatoulouseApp.class).getContext().getResourceMap(SATResults.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setMinimumSize(new java.awt.Dimension(600, 400));
        setName("Form"); // NOI18N
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        panSatisfiable.setAlignmentY(0.0F);
        panSatisfiable.setMaximumSize(new java.awt.Dimension(32767, 32767));
        panSatisfiable.setMinimumSize(null);
        panSatisfiable.setName("panSatisfiable"); // NOI18N
        panSatisfiable.setPreferredSize(null);
        panSatisfiable.setLayout(new javax.swing.BoxLayout(panSatisfiable, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel1.setIcon(resourceMap.getIcon("jLabel1.icon")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        panSatisfiable.add(jLabel1);

        jLabel5.setFont(resourceMap.getFont("jLabel5.font")); // NOI18N
        jLabel5.setForeground(resourceMap.getColor("jLabel5.foreground")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        panSatisfiable.add(jLabel5);

        jLabel2.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel2.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        panSatisfiable.add(jLabel2);

        jLabel4.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel4.setForeground(resourceMap.getColor("jLabel4.foreground")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        panSatisfiable.add(jLabel4);

        getContentPane().add(panSatisfiable);

        panInsatisfiable.setAlignmentY(0.0F);
        panInsatisfiable.setMaximumSize(new java.awt.Dimension(32767, 32767));
        panInsatisfiable.setMinimumSize(null);
        panInsatisfiable.setName("panInsatisfiable"); // NOI18N
        panInsatisfiable.setPreferredSize(null);
        panInsatisfiable.setLayout(new javax.swing.BoxLayout(panInsatisfiable, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setForeground(resourceMap.getColor("jLabel3.foreground")); // NOI18N
        jLabel3.setIcon(resourceMap.getIcon("jLabel3.icon")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        panInsatisfiable.add(jLabel3);

        jLabel6.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel6.setForeground(resourceMap.getColor("jLabel6.foreground")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        panInsatisfiable.add(jLabel6);

        getContentPane().add(panInsatisfiable);

        panValuation.setAlignmentX(0.0F);
        panValuation.setName("panValuation"); // NOI18N
        panValuation.setLayout(new javax.swing.BoxLayout(panValuation, javax.swing.BoxLayout.PAGE_AXIS));

        panValuationProposition.setName("panValuationProposition"); // NOI18N
        panValuation.add(panValuationProposition);

        panSelection.setName("panSelection"); // NOI18N
        panSelection.setLayout(new javax.swing.BoxLayout(panSelection, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        panSelection.add(jLabel7);

        txtSelection.setText(resourceMap.getString("txtSelection.text")); // NOI18N
        txtSelection.setMaximumSize(new java.awt.Dimension(2147483647, 20));
        txtSelection.setName("txtSelection"); // NOI18N
        txtSelection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtSelectionMousePressed(evt);
            }
        });
        txtSelection.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSelectionKeyReleased(evt);
            }
        });
        panSelection.add(txtSelection);

        panValuation.add(panSelection);

        getContentPane().add(panValuation);

        cmdHelp.setIcon(resourceMap.getIcon("cmdHelp.icon")); // NOI18N
        cmdHelp.setText(resourceMap.getString("cmdHelp.text")); // NOI18N
        cmdHelp.setName("cmdHelp"); // NOI18N
        cmdHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHelpActionPerformed(evt);
            }
        });
        getContentPane().add(cmdHelp);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSelectionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSelectionMousePressed
        afficherValuation();
    }//GEN-LAST:event_txtSelectionMousePressed

    private void txtSelectionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSelectionKeyReleased
        afficherValuation();
    }//GEN-LAST:event_txtSelectionKeyReleased

    private void cmdHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHelpActionPerformed
        Help.show("satunsat.html");
    }//GEN-LAST:event_cmdHelpActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SATResults dialog = new SATResults(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdHelp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel panInsatisfiable;
    private javax.swing.JPanel panSatisfiable;
    private javax.swing.JPanel panSelection;
    private javax.swing.JPanel panValuation;
    private javax.swing.JPanel panValuationProposition;
    private javax.swing.JTextField txtSelection;
    // End of variables declaration//GEN-END:variables

}
