# Fichier makefile

default: proc2 p2fils1 p2fils2

proc2: proc2.c
	gcc -o proc2 proc2.c

p2fils1: p2fils1.c
	gcc -o p2fils1 p2fils1.c

p2fils2: p2fils2.c
	gcc -o p2fils2 p2fils2.c

clean: 
	rm *.o

recomp: clean
	make
